# Generated by Django 5.2 on 2025-09-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password_plain',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
