# Generated by Django 5.2 on 2025-09-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0003_useraccount_bio_useraccount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(blank=True, choices=[('worker', 'Worker'), ('owner', 'Owner')], default='', max_length=10),
        ),
    ]
