# Generated by Django 5.2 on 2025-09-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0007_rename_upi_transaction_id_paymenttransaction_razorpay_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='booked_worker_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
