# Generated by Django 5.2 on 2025-09-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0008_paymenttransaction_booked_worker_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='booked_worker_email',
        ),
    ]
