# Generated by Django 5.2 on 2025-09-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0009_remove_paymenttransaction_booked_worker_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerjobpost',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending_accept', 'Pending Acceptance'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='workeravailability',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending_accept', 'Pending Acceptance'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
