# Generated by Django 5.2 on 2025-09-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0010_ownerjobpost_status_workeravailability_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerjobpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workeravailability',
            name='status',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
